### ISSUE TITLE
Footer Background Image and Footer Background Color options are not working

### ISSUE THREAD

**Issue by memash** [sayedwp/supernova#36]
Footer Background Image and Footer Background Color both options are not working. 

The other thing is that you will need to add a conditional tag to the footer. For example,
1. If you choose footer background color the footer background image should be replaced with the color. 
2. If you choose footer background Image the Footer Background Color should be replaced with the image.

**Comment by sayedwp** [comment]
Doesn't seem to be an issue, the background color will reflect only when there is no background image, wrote a message in customizer. Closing..
